/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class GameResult : Message
    {
        public const string RosMessageName = "roborts_msgs/GameResult";

        // game result
        public const byte DRAW = 0;
        public const byte RED_WIN = 1;
        public const byte BLUE_WIN = 2;
        public byte result { get; set; }

        public GameResult()
        {
            this.result = 0;
        }

        public GameResult(byte result)
        {
            this.result = result;
        }
    }
}
