/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class GameStatus : Message
    {
        public const string RosMessageName = "roborts_msgs/GameStatus";

        // game status
        public const byte PRE_MATCH = 0;
        public const byte SETUP = 1;
        public const byte INIT = 2;
        public const byte FIVE_SEC_CD = 3;
        public const byte ROUND = 4;
        public const byte CALCULATION = 5;
        public byte game_status { get; set; }
        public ushort remaining_time { get; set; }

        public GameStatus()
        {
            this.game_status = 0;
            this.remaining_time = 0;
        }

        public GameStatus(byte game_status, ushort remaining_time)
        {
            this.game_status = game_status;
            this.remaining_time = remaining_time;
        }
    }
}
