/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class RobotStatus : Message
    {
        public const string RosMessageName = "roborts_msgs/RobotStatus";

        // robot status
        public byte id { get; set; }
        public byte level { get; set; }
        public ushort remain_hp { get; set; }
        public ushort max_hp { get; set; }
        public ushort heat_cooling_limit { get; set; }
        public ushort heat_cooling_rate { get; set; }
        public bool gimbal_output { get; set; }
        public bool chassis_output { get; set; }
        public bool shooter_output { get; set; }

        public RobotStatus()
        {
            this.id = 0;
            this.level = 0;
            this.remain_hp = 0;
            this.max_hp = 0;
            this.heat_cooling_limit = 0;
            this.heat_cooling_rate = 0;
            this.gimbal_output = false;
            this.chassis_output = false;
            this.shooter_output = false;
        }

        public RobotStatus(byte id, byte level, ushort remain_hp, ushort max_hp, ushort heat_cooling_limit, ushort heat_cooling_rate, bool gimbal_output, bool chassis_output, bool shooter_output)
        {
            this.id = id;
            this.level = level;
            this.remain_hp = remain_hp;
            this.max_hp = max_hp;
            this.heat_cooling_limit = heat_cooling_limit;
            this.heat_cooling_rate = heat_cooling_rate;
            this.gimbal_output = gimbal_output;
            this.chassis_output = chassis_output;
            this.shooter_output = shooter_output;
        }
    }
}
