/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class RobotBonus : Message
    {
        public const string RosMessageName = "roborts_msgs/RobotBonus";

        // robot bonus
        public bool bonus { get; set; }

        public RobotBonus()
        {
            this.bonus = false;
        }

        public RobotBonus(bool bonus)
        {
            this.bonus = bonus;
        }
    }
}
