/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class RobotDamage : Message
    {
        public const string RosMessageName = "roborts_msgs/RobotDamage";

        // robot damage
        public const byte ARMOR = 0;
        public const byte OFFLINE = 1;
        public const byte EXCEED_HEAT = 2;
        public const byte EXCEED_POWER = 3;
        public byte damage_type { get; set; }
        public const byte FORWARD = 0;
        public const byte LEFT = 1;
        public const byte BACKWARD = 2;
        public const byte RIGHT = 3;
        public byte damage_source { get; set; }

        public RobotDamage()
        {
            this.damage_type = 0;
            this.damage_source = 0;
        }

        public RobotDamage(byte damage_type, byte damage_source)
        {
            this.damage_type = damage_type;
            this.damage_source = damage_source;
        }
    }
}
