/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class SupplierStatus : Message
    {
        public const string RosMessageName = "roborts_msgs/SupplierStatus";

        // supplier status
        public const byte CLOSE = 0;
        public const byte PREPARING = 1;
        public const byte SUPPLYING = 2;
        public byte status { get; set; }

        public SupplierStatus()
        {
            this.status = 0;
        }

        public SupplierStatus(byte status)
        {
            this.status = status;
        }
    }
}
