/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



using RosSharp.RosBridgeClient.MessageTypes.Geometry;

namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class TwistAccel : Message
    {
        public const string RosMessageName = "roborts_msgs/TwistAccel";

        public Twist twist { get; set; }
        public Accel accel { get; set; }

        public TwistAccel()
        {
            this.twist = new Twist();
            this.accel = new Accel();
        }

        public TwistAccel(Twist twist, Accel accel)
        {
            this.twist = twist;
            this.accel = accel;
        }
    }
}
