/* 
 * This message is auto generated by ROS#. Please DO NOT modify.
 * Note:
 * - Comments from the original code will be written in their own line 
 * - Variable sized arrays will be initialized to array of size 0 
 * Please report any issues at 
 * <https://github.com/siemens/ros-sharp> 
 */



namespace RosSharp.RosBridgeClient.MessageTypes.Roborts
{
    public class ShootCmdResponse : Message
    {
        public const string RosMessageName = "roborts_msgs/ShootCmd";

        public bool received { get; set; }

        public ShootCmdResponse()
        {
            this.received = false;
        }

        public ShootCmdResponse(bool received)
        {
            this.received = received;
        }
    }
}
